"""
Model Routing Table package.
"""

from .table import (
    DIMENSION_MAP,
    DIMENSION_FALLBACK,
    DIMENSION_DESCRIPTIONS,
    MODEL_COST_USD,
    CAPABILITY_MATRIX,
    SUBTASK_TYPE_TO_SPECIALIZATION,
    TASK_ROUTING,
    BRAIN_PHASE_DIMENSIONS,
    SWARM_PHASE_DIMENSIONS,
    DIMENSION_MAP_V2,
    DIMENSION_FALLBACK_V2,
    OLLAMA_CLOUD_MODELS,
    TASK_TYPE_TO_MODEL,
)

__all__ = [
    "DIMENSION_MAP",
    "DIMENSION_FALLBACK",
    "DIMENSION_DESCRIPTIONS",
    "MODEL_COST_USD",
    "CAPABILITY_MATRIX",
    "SUBTASK_TYPE_TO_SPECIALIZATION",
    "TASK_ROUTING",
    "BRAIN_PHASE_DIMENSIONS",
    "SWARM_PHASE_DIMENSIONS",
    "DIMENSION_MAP_V2",
    "DIMENSION_FALLBACK_V2",
    "OLLAMA_CLOUD_MODELS",
    "TASK_TYPE_TO_MODEL",
]